### ISSUE TITLE
Image contrast in dark mode

### ISSUE THREAD

**Issue by reedy** [andrew-codechimp/HA-Andrews-Arnold-Quota#21]
### System Health details

n/a

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/HA-Andrews-Arnold-Quota/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

In dark mode, various of the A&A logos are very very hard to read :(

### Reproduction steps

Enable dark mode...

![Screenshot 2023-09-26 at 00 43 48](https://github.com/andrew-codechimp/HA-Andrews-Arnold-Quota/assets/67615/eb1ac88e-99d8-49f0-910c-3d274568dda9)
![Screenshot 2023-09-26 at 00 43 56](https://github.com/andrew-codechimp/HA-Andrews-Arnold-Quota/assets/67615/2e61603e-bdcc-42c2-b4a1-2ea90227203e)
![Screenshot 2023-09-26 at 00 45 39](https://github.com/andrew-codechimp/HA-Andrews-Arnold-Quota/assets/67615/d12fd8fe-28a6-4d47-a55e-e3b30a02c10c)

### Debug logs

```text
n/a
```

**Comment by andrew-codechimp** [comment]
Thanks for the feedback, I've managed to find an inverse image on the Andrews & Arnold website and submitted to brands
https://github.com/home-assistant/brands/pull/4725
Once merged by the HA team they'll refresh after the cache period expires.

**Comment by reedy** [comment]
Thanks! :)

**Comment by reedy** [comment]
Merged and working. Looks better now

![Screenshot 2023-09-26 at 17 20 12](https://github.com/andrew-codechimp/HA-Andrews-Arnold-Quota/assets/67615/03a61ee8-39c8-4bc8-b4ff-116b3e93415c)
![Screenshot 2023-09-26 at 17 20 18](https://github.com/andrew-codechimp/HA-Andrews-Arnold-Quota/assets/67615/c60c9dab-e125-4091-b108-9b90abbc348c)
